window.C1_ARTICLES = [
  {
    id: "campus",
    title: "Prüfungen, Kurse, Nachdenken",
    kicker: "Studium",
    blurb: "Campus, Fristen und die Frage, wie man lernt.",
    sentences: [
      { de: "Bevor die Klausur [[stattfindet|stattfinden]], muss Mara lange über das Thema [[nachdenken]].", zh: "在考试举行之前，玛拉必须把这个题目好好想很久。" },
      { de: "Sie darf sich keine Ausrede [[ausdenken]], sondern muss die Folgen [[bedenken]].", zh: "她不能给自己编借口，而必须考虑到后果。" },
      { de: "Wer die Regeln nicht [[bedenkt]], [[besteht]] die Prüfung selten.", zh: "不考虑规则的人，很少能通过考试。" },
      { de: "Am Denkmal [[gedenkt]] die Uni jedes Jahr der Gründer.", zh: "大学每年都在纪念碑前缅怀创始人。" },
      { de: "Mara [[überdenkt]] ihren Plan und muss völlig [[umdenken]].", zh: "玛拉把计划重新想了一遍，必须彻底换思路。" },
      { de: "Gute Betreuung ist nicht [[wegzudenken|wegdenken]].", zh: "好的辅导是不可或缺的。" },
      { de: "Sie versucht, sich in nervöse Kommilitonen [[hineinzudenken|hineindenken]].", zh: "她试着设身处地去想那些紧张的同学。" },
      { de: "Um 6 Uhr muss sie [[aufstehen]], weil die Prüfung [[bevorsteht]].", zh: "她六点就得起床，因为考试就在眼前。" },
      { de: "Wenn sie diese Woche [[übersteht]], kann sie aufatmen.", zh: "如果她熬过这一周，就能松口气。" },
      { de: "Neue Fragen [[entstehen]] erst, wenn man den Stoff wirklich [[versteht]].", zh: "只有真正理解材料时，新问题才会产生。" },
      { de: "Sie [[belegt]] drei Kurse und muss das mit einer Mail [[belegen]].", zh: "她选了三门课，还得用一封邮件证明这一点。" },
      { de: "Nächste Woche [[legt]] sie die letzte Prüfung [[ab|ablegen]] und [[legt]] endlich die schwere Jacke [[ab|ablegen]].", zh: "下周她参加最后一场考试，也终于能脱掉那件厚外套。" },
      { de: "Eine schlechte Gewohnheit will sie ebenfalls [[ablegen]]: immer zu spät zu kommen.", zh: "她也想改掉一个坏习惯：老是迟到。" },
      { de: "Die Fakultät hat die Termine [[festgelegt|festlegen]] und die Kriterien [[dargelegt|darlegen]].", zh: "院系已经定下日期，并说明了标准。" },
      { de: "Mara [[nimmt]] an einem Workshop [[teil|teilnehmen]] und [[nimmt]] den Termin [[wahr|wahrnehmen]].", zh: "玛拉参加一个工作坊，并兑现了这个预约。" },
      { de: "Sie hat sich [[vorgenommen|vornehmen]], kleine Änderungen [[vorzunehmen|vornehmen]].", zh: "她打算做一些小改动。" },
      { de: "Zuerst [[teilt]] sie den Stoff [[ein|einteilen]] und [[teilt]] ihre Zeit streng [[ein|einteilen]].", zh: "她先把材料分类，再严格安排时间。" },
      { de: "Im Labor muss sie Daten [[angeben]], [[eingeben]] und [[erfassen]].", zh: "在实验室里她必须填写、输入并登记数据。" },
      { de: "Danach [[verfasst]] sie einen Text, [[fasst]] ihn [[zusammen|zusammenfassen]] und [[arbeitet]] ihn noch einmal [[über|überarbeiten]].", zh: "然后她写一篇文章，加以概括，再修订一遍。" },
      { de: "Ein Konzept hat sie schon [[ausgearbeitet|ausarbeiten]]; jetzt [[bearbeitet]] sie nur noch den Antrag.", zh: "方案她已经详细拟定了，现在只还在办申请。" },
      { de: "Sie [[nimmt]] an, dass Konzentration nicht [[nachlässt|nachlassen]].", zh: "她认为注意力不会减弱。" },
      { de: "Wenn der Druck doch [[nachlässt]], darf sie eine Pause [[einlegen]].", zh: "如果压力真的降下来，她可以插入一次休息。" },
    ],
  },
  {
    id: "arbeit",
    title: "Im Betrieb: Pläne umsetzen",
    kicker: "Beruf",
    blurb: "Team, Verantwortung und ein volles Projekt.",
    sentences: [
      { de: "Am Bahnhof [[kommt]] Lin [[an|ankommen]] und [[bekommt]] sofort eine Mappe.", zh: "林到达火车站，马上拿到一份材料夹。" },
      { de: "Es [[kommt]] darauf [[an|ankommen]], ob sie gegen die Deadline [[ankommt|ankommen]].", zh: "关键在于她能不能赶得上截止日期。" },
      { de: "Im Büro [[kommen]] Missverständnisse oft [[vor|vorkommen]]; ihr [[kommt]] das chaotisch [[vor|vorkommen]].", zh: "办公室里常常出现误会；在她看来这很混乱。" },
      { de: "Mit dem Gehalt [[kommt]] sie knapp [[aus|auskommen]], mit dem Chef aber gut [[aus|auskommen]].", zh: "工资她勉强够用，但和上司相处得不错。" },
      { de: "Neue Ideen [[kommen]] auf, und die Firma muss für Fehler [[aufkommen]].", zh: "新想法兴起，公司也必须为错误承担责任。" },
      { de: "Lin [[kommt]] ihrer Pflicht [[nach|nachkommen]] und [[kommt]] den anderen im Tempo [[nach|nachkommen]].", zh: "林履行自己的义务，进度上也跟得上别人。" },
      { de: "Ein Lieferproblem ist knapp [[entkommen]]; niemand ist [[umgekommen]].", zh: "一次供货问题勉强逃过；没有人丧生。" },
      { de: "Mit der Software [[kommt]] sie langsam [[zurecht|zurechtkommen]].", zh: "这套软件她慢慢应付得来了。" },
      { de: "Der Chef [[kommt]] ihr entgegen und sagt, ihr [[stehe]] eine Schulung [[zu|zustehen]].", zh: "上司向她让步，并说她有权得到一次培训。" },
      { de: "Probleme [[kommen]] auf sie [[zu|zukommen]].", zh: "问题向她逼近。" },
      { de: "Sie will Verantwortung [[übernehmen]] und sich für das Team [[einsetzen]].", zh: "她想承担责任，并为团队出力。" },
      { de: "Die Firma [[setzt]] neue Leute [[ein|einsetzen]] und will die Reform [[durchsetzen]].", zh: "公司任用新人，并想把改革贯彻下去。" },
      { de: "Lin muss sich selbst [[durchsetzen]] und die Pläne [[umsetzen]].", zh: "林必须自己站稳，并把计划落地。" },
      { de: "Letztes Jahr hat die Abteilung viel Umsatz [[umgesetzt|umsetzen]].", zh: "去年这个部门做成了很高的营业额。" },
      { de: "Das [[setzt]] Disziplin [[voraus|voraussetzen]].", zh: "这以纪律为前提。" },
      { de: "Sie [[setzt]] sich mit den Zahlen [[auseinander|auseinandersetzen]] und [[setzt]] die Reihe [[fort|fortsetzen]].", zh: "她认真处理这些数字，并把系列工作继续下去。" },
      { de: "Ein Platz ist schon [[besetzt]]; eine Stelle soll neu [[besetzt]] werden.", zh: "一个座位已被占用；一个职位要重新填补。" },
      { de: "Man wollte sie [[versetzen]], was alle in Aufregung [[versetzte|versetzen]].", zh: "有人想把她调走，这让大家都紧张起来。" },
      { de: "Sie [[setzen]] einen Termin [[an|ansetzen]] und [[setzen]] zu einer Präsentation [[an|ansetzen]].", zh: "他们定下一个时间，并开始准备演示。" },
      { de: "Wegen Krankheit [[setzt]] das Team die Sitzung [[aus|aussetzen]].", zh: "因为生病，小组暂停会议。" },
      { de: "Niemand darf Kollegen einer Gefahr [[aussetzen]].", zh: "谁也不能把同事置于危险之中。" },
      { de: "An dem Entwurf hat Lin nichts [[auszusetzen|aussetzen]].", zh: "对这份草稿林没什么可挑剔的。" },
      { de: "Der alte Leiter wurde [[abgesetzt|absetzen]]; Fahrtkosten kann sie steuerlich [[absetzen]].", zh: "旧领导被免职了；路费她可以报税扣除。" },
      { de: "Sie [[arbeitet]] mit Legal [[zusammen|zusammenarbeiten]]; Praktikanten [[arbeitet]] sie [[ein|einarbeiten]].", zh: "她和法律部门合作；她带实习生上手。" },
      { de: "Selbst [[arbeitet]] sie sich rasch [[ein|einarbeiten]] und [[arbeitet]] nebenbei [[mit|mitarbeiten]].", zh: "她自己也很快熟悉工作，并一起参与。" },
      { de: "Ein Kollege [[arbeitet]] ihr [[zu|zuarbeiten]], obwohl alle [[überarbeitet]] sind.", zh: "一位同事给她打下手，尽管大家都已经过劳。" },
      { de: "Zusammen [[erarbeiten]] sie eine Lösung und [[arbeiten]] die Vergangenheit des Projekts [[auf|aufarbeiten]].", zh: "他们一起做出方案，并清理这个项目的旧账。" },
    ],
  },
  {
    id: "amt",
    title: "Wohnen, Amt und Geld",
    kicker: "Alltag",
    blurb: "Ummelden, Miete, Konto.",
    sentences: [
      { de: "Jonas [[meldet]] sich im Bürgeramt [[an|anmelden]] und will später ein Gewerbe [[anmelden]].", zh: "约纳斯在市民局登记，以后还想登记营业。" },
      { de: "Nach dem Umzug [[meldet]] er sich in der alten Stadt [[ab|abmelden]] und hier [[um|anmelden / ummelden]].", zh: "搬家后他在旧城市注销，并在这里更改住址登记。" },
      { de: "In der Schlange [[meldet|sich melden]] er sich, wenn er dran ist.", zh: "排队时轮到他就举手示意。" },
      { de: "Die Zeitung [[vermeldet]] neue Gebühren.", zh: "报纸宣布了新的费用。" },
      { de: "Er [[hebt]] Bargeld [[ab|abheben]]; das Flugzeug der Eltern [[hebt]] am Abend [[ab|abheben]].", zh: "他取现金；父母的飞机晚上起飞。" },
      { de: "Mit einem roten Schal [[hebt]] er sich von der Menge [[ab|abheben]].", zh: "一条红围巾让他在人群里很显眼。" },
      { de: "Die Stadt will die Gebühren [[anheben]] und [[erhebt]] schon eine kleine Taxe.", zh: "城市想提高费用，并且已经在征收一小笔税。" },
      { de: "Er [[erhebt|erheben]] sich von der Bank, [[erhebt|erheben]] Daten für einen Antrag und [[erhebt|erheben]] Anspruch auf Wohngeld.", zh: "他从长椅上站起来，为申请采集数据，并要求住房补贴。" },
      { de: "Die Broschüre [[hebt]] drei Regeln [[hervor|hervorheben]].", zh: "小册子强调三条规则。" },
      { de: "Vor dem Haus [[heben]] Arbeiter eine Grube [[aus|ausheben]].", zh: "房前工人挖了一个坑。" },
      { de: "Einen alten Schlüssel [[hebt]] er [[auf|aufheben]]; ein Verbot wurde gestern [[aufgehoben|aufheben]].", zh: "一把旧钥匙他留着；一项禁令昨天被取消了。" },
      { de: "Er [[gibt]] zu viel Geld [[aus|ausgeben]] und darf nicht [[angeben]].", zh: "他花钱太多，也不该炫耀。" },
      { de: "Am Schalter [[gibt]] er das Gepäck [[auf|aufgeben]] und will nicht [[aufgeben]].", zh: "在柜台他把行李托运，但不想放弃。" },
      { de: "Die Behörde [[gibt]] ihm Formulare [[auf|aufgeben]].", zh: "机关给他布置了表格任务。" },
      { de: "Ein Betrüger [[gibt]] sich als Beamter [[aus|ausgeben]].", zh: "一个骗子冒充官员。" },
      { de: "Die Rechnung [[ergibt]] 42 Euro; er will sich dem Druck nicht [[ergeben]].", zh: "账单得出 42 欧元；他不愿向压力投降。" },
      { de: "Er [[gibt]] den Fehler [[zu|zugeben]] und [[gibt]] bei der Miete nicht [[nach|nachgeben]].", zh: "他承认错误，房租上却不让步。" },
      { de: "Den Vertrag [[übergibt]] er der Hausverwaltung.", zh: "他把合同交给物业。" },
      { de: "Die Stadt [[gibt]] ein Heft [[heraus|herausgeben]]; der Automat [[gibt]] Wechselgeld [[heraus|herausgeben]].", zh: "市政出版一本小册子；机器找出零钱。" },
      { de: "Sie [[vergibt]] ihm die Verspätung, [[vergibt]] den Auftrag neu und will keine Chance [[vergeben]].", zh: "她原谅他迟到，把订单重新发包，也不想错过机会。" },
      { de: "Er [[gibt|vorgeben]] vor, alles verstanden zu haben, [[umgeben]] von Akten.", zh: "他声称都懂了，周围全是卷宗。" },
      { de: "Die Kosten [[nehmen]] ab, das Gewicht [[nimmt]] zu.", zh: "费用在减少，体重却在增加。" },
      { de: "Der Schalter [[nimmt]] ihm den Ausweis [[ab|abnehmen]].", zh: "窗口把他的证件接过去。" },
      { de: "Er [[nimmt]] die Hilfe [[an|annehmen]] und [[nimmt]] neue Nachbarn [[auf|aufnehmen]].", zh: "他接受帮助，并收留新邻居。" },
      { de: "Fotos [[nimmt]] er selbst [[auf|aufnehmen]].", zh: "照片他自己拍。" },
    ],
  },
  {
    id: "medien",
    title: "Meinung, Medien, Gesellschaft",
    kicker: "Debatte",
    blurb: "Foren, Berichte und wie man miteinander umgeht.",
    sentences: [
      { de: "Viele [[gehen]] abends [[aus|ausgehen]] und [[gehen]] von falschen Zahlen [[aus|ausgehen]].", zh: "许多人晚间出门，却从错误数字出发。" },
      { de: "Das Thema [[geht]] alle [[an|angehen]]; man muss es endlich [[angehen]].", zh: "这事关系到所有人；必须着手处理。" },
      { de: "Die Redaktion [[geht]] auf Kritik [[ein|eingehen]]; sonst [[geht]] das Vertrauen [[ein|eingehen]].", zh: "编辑部回应批评；否则信任会枯死。" },
      { de: "Sie [[geht]] ruhig [[vor|vorgehen]], denn Fairness [[geht]] vor.", zh: "他们行事冷静，因为公平优先。" },
      { de: "Man muss mit Quellen sorgfältig [[umgehen]] und darf Regeln nicht [[umgehen]].", zh: "必须谨慎对待来源，也不可规避规则。" },
      { de: "Wer unbequeme Stimmen [[übergeht]], [[geht]] schnell zu Polemik [[über|übergehen]].", zh: "谁略过刺耳的声音，很快就会转向论战。" },
      { de: "Ohne Debatte [[geht]] eine Demokratie [[unter|untergehen]].", zh: "没有辩论，民主就会沉没。" },
      { de: "Der Sonne gleich [[geht]] manchen plötzlich ein Gedanke [[auf|aufgehen]].", zh: "有些人会像日出一样突然想通一件事。" },
      { de: "Die Stadt [[begeht]] ein Fest, während andere einen Fehler [[begehen]].", zh: "城市在庆祝节日，另一些人却在犯错。" },
      { de: "Die Zeit [[vergeht]]; Gewalt, wer sich an anderen [[vergeht]], gehört vors Gericht.", zh: "时间流逝；对他人施暴的人应上法庭。" },
      { de: "Redakteure [[gehen]] den Text [[durch|durchgehen]]; nicht jede Behauptung darf einfach [[durchgehen]].", zh: "编辑把文章过一遍；不是每个说法都能蒙混过关。" },
      { de: "Ein Autor [[erfindet]] Beispiele, [[empfindet]] Kritik als hart und [[findet]] sich im Archiv [[zurecht|zurechtfinden]].", zh: "作者编造例子，觉得批评刺耳，并在档案里找到方向。" },
      { de: "Das Büro [[befindet]] sich im dritten Stock; ein Gremium [[befindet]] über die Beschwerde.", zh: "办公室在三楼；一个委员会对投诉作出裁定。" },
      { de: "Sie [[finden]] die Quelle [[heraus|herausfinden]] und [[finden]] Chaos [[vor|vorfinden]].", zh: "他们查明来源，并发现现场一片混乱。" },
      { de: "Mit der Lage muss man sich [[abfinden]]; Opfern wird eine Summe [[abgefunden|abfinden]].", zh: "这种局面只能接受；受害者会得到一笔补偿。" },
      { de: "Ein Bericht [[bildet]] die Stadt [[ab|abbilden]]; neue Rituale [[bilden]] sich [[heraus|herausbilden]].", zh: "一篇报道描绘这座城市；新的仪式逐渐形成。" },
      { de: "Mancher [[bildet|einbilden]] sich ein, alles zu wissen.", zh: "有人自以为什么都懂。" },
      { de: "Die Regierung wird [[umgebildet|umbilden]]; ein Modell wird [[nachgebildet|nachbilden]].", zh: "政府将被改组；一个模型会被仿制。" },
      { de: "Junge Leute werden [[ausgebildet|ausbilden]], [[bilden]] sich [[weiter|weiterbilden]] und [[bilden]] sich [[fort|fortbilden]].", zh: "年轻人接受培训，继续进修，参加继续教育。" },
      { de: "Kommentare [[teilen]] sie in Töne [[unter|unterteilen]] und [[teilen]] Aufmerksamkeit [[auf|aufteilen]].", zh: "他们把评论按语气细分，并把注意力分开。" },
      { de: "Die Redaktion [[teilt]] Aufgaben [[zu|zuteilen]] und [[teilt]] Flyer [[aus|austeilen]].", zh: "编辑部分配任务，并分发传单。" },
      { de: "Manche [[teilen]] nur Kritik [[aus|austeilen]].", zh: "有些人只会大加批评。" },
      { de: "Fakten [[teilt]] man den Lesern [[mit|mitteilen]] und [[verteilt]] sie auf Kanäle.", zh: "事实告知读者，并分发到各渠道。" },
    ],
  },
  {
    id: "regeln",
    title: "Fristen, Haltung, Zusammenhalt",
    kicker: "Organisation",
    blurb: "Was man einhält – und was man einander vorhält.",
    sentences: [
      { de: "Wer Fristen [[einhält|einhalten]], [[behält]] den Überblick.", zh: "遵守期限的人能保持全局。" },
      { de: "Sie [[erhält]] die Bestätigung und [[erhält]] das alte Gebäude.", zh: "她收到确认，并维护那栋老楼。" },
      { de: "Der Vertrag [[enthält]] Klauseln; bei der Abstimmung [[enthält]] sie sich.", zh: "合同包含条款；表决时她弃权。" },
      { de: "Abends [[unterhalten]] sie sich, [[unterhalten]] Gäste und [[unterhalten]] die Website.", zh: "晚上他们聊天，招待客人，并维护网站。" },
      { de: "In der Kritik [[verhält]] sie sich ruhig.", zh: "面对批评她表现得很冷静。" },
      { de: "Der Verein [[hält]] eine Versammlung [[ab|abhalten]] und will niemanden vom Mitmachen [[abhalten]].", zh: "协会举行集会，也不想阻止任何人参与。" },
      { de: "Stau [[hält]] sie [[auf|aufhalten]]; sie [[hält]] sich oft im Archiv [[auf|aufhalten]].", zh: "堵车耽搁了她；她常常待在档案室。" },
      { de: "Den Lärm kann sie kaum [[aushalten]].", zh: "噪音她几乎受不了。" },
      { de: "Trotzdem [[hält]] sie an ihrem Ziel [[fest|festhalten]] und [[hält]] jedes Argument [[fest|festhalten]].", zh: "尽管如此她仍坚持目标，并把每条论据记下来。" },
      { de: "Niemand sollte ihr Unerfahrenheit [[vorhalten]].", zh: "谁也不该拿没经验指责她。" },
      { de: "Sie [[hält]] sich [[zurück|zurückhalten]] und [[hält]] keine Infos [[zurück|zurückhalten]].", zh: "她为人克制，却不隐瞒信息。" },
      { de: "Die beiden [[verstehen]] sich; das Projekt [[besteht]] aus drei Teilen.", zh: "两人合得来；项目由三部分组成。" },
      { de: "Sie [[besteht]] auf Klarheit, solange der Verein [[besteht]].", zh: "只要协会还存在，她就坚持要清楚。" },
      { de: "Er [[gesteht]] den Irrtum und will für das Team [[einstehen]].", zh: "他承认失误，并愿为团队担责。" },
      { de: "Einer Versuchung zu [[widerstehen]] fällt schwer.", zh: "要抵制诱惑并不容易。" },
      { de: "Einen Kollegen kann sie nicht [[ausstehen]]; eine Rechnung [[steht]] noch [[aus|ausstehen]].", zh: "有个同事她受不了；一笔账还没付。" },
      { de: "Sie [[überlegt]], ob sie Widerspruch [[einlegt|einlegen]].", zh: "她在考虑要不要提出异议。" },
      { de: "Gemüse [[legt]] sie selbst [[ein|einlegen]].", zh: "蔬菜她自己腌。" },
      { de: "Kritik als Angriff [[auszulegen|auslegen]] wäre falsch; manchmal [[legt]] sie für andere Geld [[aus|auslegen]].", zh: "把批评解释成攻击是错的；有时她会给别人垫钱。" },
      { de: "Einen Termin [[verlegen]] sie, ein Buch [[verlegen]] sie, und den Schlüssel hat jemand [[verlegt|verlegen]].", zh: "他们改期，出版一本书，钥匙却被人放丢了。" },
      { de: "Eine Behauptung [[widerlegt]] sie; dem Chef [[legt]] sie Ruhe [[nahe|nahelegen]].", zh: "她驳斥一个说法，并暗示上司冷静一点。" },
      { de: "Einen Brief [[fasst|abfassen]] sie [[ab|abfassen]], [[fasst|erfassen]] das Problem rasch und [[fasst|sich fassen]] sich dann.", zh: "她草拟一封信，抓住问题要点，然后让自己冷静下来。" },
      { de: "Bitte [[fassen|sich fassen]] Sie sich kurz und [[fassen|anfassen]] Sie den Ordner nicht unnötig [[an|anfassen]].", zh: "请说简短些，也别随便用手碰文件夹。" },
      { de: "Sie [[fasst]] die Lage als Chance [[auf|auffassen]]; der Plan [[umfasst]] fünf Punkte.", zh: "她把局面理解为机会；计划涵盖五点。" },
      { de: "Von Panik darf niemand [[erfasst]] werden.", zh: "谁也不该被恐慌攫住。" },
    ],
  },
  {
    id: "stadt",
    title: "Stadt, Technik, Verträge",
    kicker: "Infrastruktur",
    blurb: "Anschließen, abschließen, erschließen.",
    sentences: [
      { de: "Die Stadt [[schließt]] die Baustelle [[ab|abschließen]] und [[schließt]] mit der Firma einen Vertrag [[ab|abschließen]].", zh: "城市结束工地施工，并与公司签订合同。" },
      { de: "Techniker [[schließen]] die Leitungen [[an|anschließen]]; Bürger [[schließen]] sich der Kritik [[an|anschließen]].", zh: "技术员接上管线；市民赞同这些批评。" },
      { de: "Man darf Nachbarn nicht [[ausschließen]] und darf Risiken nicht [[ausschließen]].", zh: "既不能把邻居排除在外，也不能排除风险。" },
      { de: "Wertsachen [[schließt]] man [[ein|einschließen]], Kosten inklusive Service.", zh: "贵重物品要锁起来，费用已包括服务。" },
      { de: "Der Rat [[beschließt]] den Plan und [[erschließt]] ein neues Gebiet.", zh: "议会作出决议，并开发一块新区。" },
      { de: "Aus den Akten [[erschließt]] man die Absicht.", zh: "从卷宗里可以推断意图。" },
      { de: "Morgens [[schließt]] der Hausmeister [[auf|aufschließen]].", zh: "早上管家开门。" },
      { de: "Nachts [[verschließt]] er das Tor und [[verschließt]] sich nicht neuen Ideen.", zh: "夜里他把门锁上，却不对新想法封闭自己。" },
      { de: "Alte Lampen [[ersetzt]] man; Geräte [[setzt]] man sorgfältig [[ein|einsetzen]].", zh: "旧灯被替换；设备被谨慎投入使用。" },
      { de: "Wer den Ort [[verlässt]], soll sich auf den Fahrplan [[verlassen]].", zh: "离开此地的人应信赖时刻表。" },
      { de: "Die Stadt [[lässt]] E-Roller [[zu|zulassen]] und [[lässt]] niemanden ohne Grund [[entlassen]].", zh: "城市允许电动滑板，也不会无故解雇人。" },
      { de: "Lärm [[unterlassen]]! Den Schlüssel [[überlässt]] man der Nachbarin.", zh: "请停止制造噪音！钥匙交给邻居。" },
      { de: "Nach 22 Uhr [[lässt]] man nur Bekannte [[ein|einlassen]] und [[lässt]] sich nicht auf Streit [[ein|einlassen]].", zh: "晚上十点后只放熟人进来，也不卷入争吵。" },
      { de: "Der Regen [[lässt]] [[nach|nachlassen]]; der Markt [[lässt]] im Preis [[nach|nachlassen]].", zh: "雨小了；市场上价格也松了。" },
      { de: "Eine Zeile darf man [[auslassen]], aber nicht die Wut an anderen [[auslassen]].", zh: "可以省略一行，却不能拿别人出气。" },
      { de: "Bitte [[hinterlassen]] Sie eine Nachricht und [[lassen]] den Ärger [[los|loslassen]].", zh: "请留下口信，并把火气放开。" },
      { de: "Neue Netze [[unternehmen]] viel, damit Daten sicher bleiben.", zh: "新网络做很多事，好让数据保持安全。" },
    ],
  },
  {
    id: "alltag",
    title: "Alltag, Körper, kleine Krisen",
    kicker: "Leben",
    blurb: "Was man wahrnimmt – und was man hinnehmen muss.",
    sentences: [
      { de: "Noel [[nimmt]] die Chance [[wahr|wahrnehmen]] und [[entnimmt]] dem Brief die Adresse.", zh: "诺埃尔抓住机会，并从信里得知地址。" },
      { de: "Kritik [[nimmt]] er [[hin|hinnehmen]], auch wenn sie wehtut.", zh: "批评他忍下来，即使难受。" },
      { de: "Er [[benimmt]] sich ruhig, bis die Polizei einen Dieb [[festnimmt|festnehmen]].", zh: "他举止平静，直到警察逮捕一个小偷。" },
      { de: "Am Abend [[unternehmen]] Freunde etwas Kleines.", zh: "晚上朋友们搞了点小活动。" },
      { de: "Sie [[schließen]] nicht aus, dass der Stress [[zunimmt|zunehmen]] und der Appetit [[abnimmt|abnehmen]].", zh: "他们不排除压力会增加、食欲会下降。" },
      { de: "Wer sich nicht [[meldet|sich melden]], [[bekommt|bekommen]] keine Schicht.", zh: "不联系的人排不上班。" },
      { de: "Ein Satz geht ihr nicht aus dem Kopf, und sie [[geht]] das Protokoll noch einmal [[durch|durchgehen]].", zh: "一句话在她脑子里挥之不去，她又把记录过了一遍。" },
      { de: "Sie [[fasst]] sich, [[fasst]] den Becher [[an|anfassen]] und trinkt.", zh: "她让自己冷静，握住杯子，喝了一口。" },
      { de: "Die Küche [[umfasst]] wenig Platz, [[umgeben]] von Kartons.", zh: "厨房地方很小，周围都是纸箱。" },
      { de: "Er [[findet]] den Zettel, den er gestern [[vorfand|vorfinden]] hatte, wieder.", zh: "他又找到昨天到达时看到的那张条子。" },
      { de: "Dass der Bus ausfällt, [[kommt]] häufig [[vor|vorkommen]].", zh: "公交车取消是常有的事。" },
      { de: "Gegen den Regen [[kommt]] niemand [[an|ankommen]].", zh: "谁也抗不过这场雨。" },
      { de: "Sie [[kommt]] auf die Nachbarin [[zu|zukommen]] und [[kommt]] ihr ein Stück [[entgegen|entgegenkommen]].", zh: "她走向邻居，并迎上几步。" },
      { de: "Ihm [[kommt]] Ruhe [[zu|zukommen]], wenn er die Tür [[abschließt|abschließen]].", zh: "他把门锁上时，安宁才属于他。" },
      { de: "Ein altes Radio ist nicht [[wegzudenken|wegdenken]].", zh: "那台旧收音机是不可或缺的。" },
      { de: "Sie [[überdenkt]] den Tag und [[denkt]] an die Oma [[nach|nachdenken]].", zh: "她把这一天重新想一遍，并思念奶奶。" },
    ],
  },
  {
    id: "rest",
    title: "Was noch offen bleibt",
    kicker: "Nachtrag",
    blurb: "Die letzten Stellen, damit keine用法漏掉。",
    sentences: [
      { de: "Ein Text wird noch einmal [[bearbeitet|bearbeiten]], bis er sitzt.", zh: "文章还要再加工，直到妥帖。" },
      { de: "Sie [[arbeitet]] ein Konzept [[aus|ausarbeiten]] und [[erarbeitet]] die letzte Tabelle.", zh: "她拟定方案，并做出最后一张表。" },
      { de: "Der Ton darf nicht [[nachlassen]]; im Schlussverkauf [[lässt]] das Geschäft [[nach|nachlassen]].", zh: "语气不该松劲；清仓时店家会降价。" },
      { de: "Daten muss man [[erfassen]], nicht nur [[angeben]].", zh: "数据必须登记，不能只口头报一下。" },
      { de: "Wer sich kurz [[fasst]], [[fasst]] trotzdem den Kern.", zh: "说得短，仍然能抓住要点。" },
      { de: "Die Mappe [[umfasst]] alles, was der Antrag [[enthält]].", zh: "文件夹涵盖申请里包含的一切。" },
      { de: "Sie [[schließt]] ein Risiko nicht [[aus|ausschließen]] und [[schließt]] das Büro [[ab|abschließen]].", zh: "她不排除风险，并把办公室锁上。" },
      { de: "Bitte [[schließen]] Sie das Fenster [[auf|aufschließen]] und [[schließen]] sich uns [[an|anschließen]].", zh: "请打开窗户，并加入我们。" },
      { de: "Man [[schließt]] Wertsachen [[ein|einschließen]] und [[verschließt]] den Schrank.", zh: "把贵重物品锁进柜子，再把柜门封上。" },
      { de: "Der Gemeinderat [[beschließt]] Licht, um das Ufer zu [[erschließen]].", zh: "市政会决议装灯，以开发河岸。" },
      { de: "Aus einem Satz [[erschließt]] sie die Haltung des Autors.", zh: "她从一句话推断作者的态度。" },
      { de: "Er [[lässt]] die Türklinke [[los|loslassen]] und [[hinterlässt]] nur ein Lächeln.", zh: "他放开门把手，只留下一个微笑。" },
      { de: "Eine Zeile [[lässt]] sie [[aus|auslassen]], Wut [[lässt]] sie nicht an der Katze [[aus|auslassen]].", zh: "她省略一行，却不拿猫出气。" },
      { de: "Gäste [[lässt]] sie [[ein|einlassen]], Streit [[lässt]] sie bleiben.", zh: "她放客人进来，争吵则不做。" },
      { de: "Lärm [[unterlassen]] sie; den Rest [[überlassen]] sie dem Zufall.", zh: "他们停止制造噪音；其余交给偶然。" },
      { de: "Die Firma [[lässt]] Homeoffice [[zu|zulassen]] und [[entlässt]] niemanden leichtfertig.", zh: "公司允许居家办公，也不会轻易解雇人。" },
      { de: "Wer den Raum [[verlässt]], [[verlässt]] sich auf den Kollegen.", zh: "离开房间的人信赖同事。" },
      { de: "Sie [[nimmt]] das Angebot [[an|annehmen]] und [[nimmt]] an, dass es fair ist.", zh: "她接受提议，并认为这是公平的。" },
      { de: "Neue Leute [[nimmt]] das Team [[auf|aufnehmen]] und [[nimmt]] das Gespräch [[auf|aufnehmen]].", zh: "小组接收新人，并开始谈话。" },
      { de: "Der Lärm [[nimmt]] ab; die Liste [[nimmt]] zu.", zh: "噪音在减；清单在增。" },
      { de: "Sie [[nimmt]] ihm die Tasche [[ab|abnehmen]].", zh: "她接过他的包。" },
      { de: "Änderungen [[nimmt]] sie [[vor|vornehmen]], wie sie es sich [[vorgenommen|vornehmen]] hat.", zh: "她进行修改，正如她事先打算的。" },
      { de: "Das [[geht]] sie etwas [[an|angehen]], also [[geht]] sie das Problem [[an|angehen]].", zh: "这和她有关，于是她着手处理。" },
      { de: "Die Blume [[geht]] ohne Wasser [[ein|eingehen]]; sie [[geht]] trotzdem auf jede Frage [[ein|eingehen]].", zh: "花没有水会枯死；她却仍回应每个问题。" },
      { de: "Was hier [[vorgeht|vorgehen]], [[geht]] der Ruhe vor.", zh: "这里发生的事，比安静更优先。" },
      { de: "Mit Stress [[umzugehen|umgehen]] heißt nicht, ihn zu [[umgehen]].", zh: "应对压力并不等于绕开它。" },
      { de: "Die Sonne [[geht]] [[unter|untergehen]] und [[geht]] morgen wieder [[auf|aufgehen]].", zh: "太阳落下，明天还会升起。" },
      { de: "Ein Fest [[begehen]] und keinen Betrug [[begehen]]: das bleibt die Linie.", zh: "庆祝节日、不欺诈：这条线不变。" },
    ],
  },
];
