window.C1_ARTICLES = [
  {
    id: "probeklausur",
    title: "Die Probeklausur",
    kicker: "Mara",
    blurb: "模拟考砸了以后，她把备考方式整套换掉。",
    sentences: [
      { de: "Mara hatte sich [[eingebildet|einbilden]], sie könne die C1-Prüfung bestehen, wenn sie nur genug Listen lerne.", zh: "玛拉曾自以为：只要把清单背够，就能通过 C1。" },
      { de: "Dann [[fand]] die Probeklausur [[statt|stattfinden]], und das Ergebnis lag weit unter dem, was sie [[angenommen|annehmen]] hatte.", zh: "接着模拟考举行了，成绩远低于她的预期。" },
      { de: "Auf dem Heimweg musste sie lange über den Fehler [[nachdenken]]: Sie hatte den Text gelesen, aber die Argumente nicht wirklich [[erfasst|erfassen]].", zh: "回家路上她把错误想了很久：文章读了，论点却没真正抓住。" },
      { de: "Eine Ausrede wollte sie sich nicht [[ausdenken]].", zh: "她不想再给自己编借口。" },
      { de: "Wenn sie die Folgen nicht [[bedachte|bedenken]], würde sie in vier Wochen dieselbe Note [[bekommen]].", zh: "若不考虑后果，四周后还会拿到同样的分数。" },
      { de: "Also [[überdachte|überdenken]] sie den ganzen Plan und beschloss, völlig [[umzudenken|umdenken]].", zh: "于是她把计划重新想过，决定彻底换思路。" },
      { de: "Am nächsten Tag [[stand]] sie um sechs [[auf|aufstehen]] und [[nahm]] zum ersten Mal einen Sprechstundentermin wirklich [[wahr|wahrnehmen]].", zh: "第二天她六点起床，第一次真正去赴了答疑时间。" },
      { de: "Die Dozentin [[legte]] ihr [[nahe|nahelegen]], weniger zu sammeln und mehr zu schreiben.", zh: "老师暗示她：少堆积，多动笔。" },
      { de: "Mara [[schloss]] sich dem Rat [[an|anschließen]], obwohl er unbequem war.", zh: "尽管不舒服，玛拉还是听从了这个建议。" },
      { de: "Sie [[legte]] die Gewohnheit [[ab|ablegen]], bis Mitternacht am Handy zu hängen, [[teilte]] den Stoff in kleine Pakete [[ein|einteilen]] und [[arbeitete]] drei kurze Texte [[aus|ausarbeiten]].", zh: "她改掉熬夜刷手机的习惯，把材料分成小包，并详细写出三篇短文。" },
      { de: "Jeden Abend [[fasste]] sie eine Seite [[zusammen|zusammenfassen]] und [[arbeitete]] sie am Morgen noch einmal [[über|überarbeiten]].", zh: "每天晚上她概括一页，早上再修订一遍。" },
      { de: "Zwei Kommilitonen [[arbeiteten]] mit ihr [[zusammen|zusammenarbeiten]]; einer [[arbeitete]] ihr zu, wenn sie stecken blieb.", zh: "两个同学和她一起学；卡住时有人给她打下手。" },
      { de: "Die echte Prüfung [[stand]] dann plötzlich [[bevor|bevorstehen]].", zh: "真正的考试突然就在眼前了。" },
      { de: "Mara [[verstand]] den ersten Text sofort, [[ging]] auf die Leitfrage [[ein|eingehen]] und [[legte]] die Klausur am Nachmittag [[ab|ablegen]].", zh: "第一篇文章她马上看懂，紧扣导引问题作答，下午考完了笔试。" },
      { de: "Als sie das Gebäude [[verließ|verlassen]], [[legte]] sie die schwere Glücksjacke [[ab|ablegen]] und atmete endlich aus.", zh: "离开大楼时，她脱掉那件厚厚的幸运外套，终于吐出一口气。" },
      { de: "Ob sie [[bestanden|bestehen]] hatte, wusste sie noch nicht.", zh: "过没过，她当时还不知道。" },
      { de: "Aber sie wusste wenigstens, dass sie diesmal nicht nur Listen gelernt, sondern den Text wirklich verstanden hatte.", zh: "但她至少知道：这一次她不只是背了清单，而是真的读懂了文章。" },
    ],
  },
  {
    id: "erster-monat",
    title: "Der erste Monat",
    kicker: "Lin",
    blurb: "入职第一周就乱，截止日期却不会等人。",
    sentences: [
      { de: "Als Lin am Montag im Büro [[ankam|ankommen]], [[kam]] ihr alles laut und unfertig [[vor|vorkommen]].", zh: "周一林走进办公室时，一切在她看来又吵又没就绪。" },
      { de: "Es [[kam]] vor allem darauf [[an|ankommen]], den Bericht bis Freitag fertigzustellen.", zh: "关键在于周五前把报告做完。" },
      { de: "Gegen diese Frist [[kam]] sie allein nicht [[an|ankommen]].", zh: "单靠她自己，赶不上这个期限。" },
      { de: "Der alte Leiter war am Freitag zuvor [[abgesetzt|absetzen]] worden, eine Kollegin sollte [[versetzt|versetzen]] werden, und die Stimmung war gereizt.", zh: "前一个周五旧领导被免职，一位同事要被调走，气氛很冲。" },
      { de: "Lin [[übernahm]] trotzdem die Verantwortung für den Mittelteil und [[setzte]] sich für das Team [[ein|einsetzen]].", zh: "尽管如此，林还是接下了中间部分的责任，并为小组出力。" },
      { de: "Sie [[setzte]] sich zuerst mit den Zahlen [[auseinander|auseinandersetzen]], [[erfasste]] die Lücken und [[teilte]] die Arbeit neu [[auf|aufteilen]].", zh: "她先认真对付那些数字，抓住缺口，再把工作重新分摊。" },
      { de: "Praktikant Jan [[arbeitete]] sie [[ein|einarbeiten]]; er [[arbeitete]] sich überraschend schnell [[ein|einarbeiten]] und [[arbeitete]] von da an [[mit|mitarbeiten]].", zh: "她带实习生扬上手；他熟悉得很快，从那以后就一起干。" },
      { de: "Mit der Rechtsabteilung [[arbeitete]] Lin [[zusammen|zusammenarbeiten]], weil ein Satz im Entwurf juristisch nicht [[durchgehen]] durfte.", zh: "她和法律部合作，因为草稿里有一句在法律上不能蒙混过关。" },
      { de: "Am Mittwoch [[setzte]] das Team die Sitzung kurz [[aus|aussetzen]], weil Jan Fieber hatte.", zh: "周三小组把会暂停了一下，因为扬发烧了。" },
      { de: "Niemand wollte ihn einer Gefahr [[aussetzen]]; die anderen [[nahmen]] die zusätzliche Stunde [[hin|hinnehmen]].", zh: "谁也不想把他置于危险中；别人把多出来的一小时忍了下来。" },
      { de: "Donnerstag [[setzten]] sie einen neuen Termin [[an|ansetzen]] und [[setzten]] zur Endfassung [[an|ansetzen]].", zh: "周四他们定了新时间，开始收尾。" },
      { de: "Lin [[gab]] zu, dass der erste Entwurf zu vage gewesen war, [[gab]] aber bei der Kernaussage nicht [[nach|nachgeben]].", zh: "林承认初稿太含糊，但在核心表述上没有让步。" },
      { de: "Am Freitagmorgen [[übergab]] sie die Mappe der Chefin.", zh: "周五早上她把文件夹交给上司。" },
      { de: "Die Präsentation [[fand]] statt, der Plan wurde [[umgesetzt|umsetzen]], und zum ersten Mal [[kam]] Lin mit dem Tempo der anderen [[zurecht|zurechtkommen]].", zh: "演示举行了，计划落地了，林第一次跟得上别人的节奏。" },
      { de: "Abends [[unterhielten]] sie sich kurz in der Küche.", zh: "晚上他们在厨房短短聊了几句。" },
      { de: "Jan sagte, ohne Lins Einsatz wäre der Bericht [[untergegangen|untergehen]].", zh: "扬说，没有林出力，这份报告早就沉了。" },
      { de: "Lin [[hielt]] sich [[zurück|zurückhalten]] und lächelte nur.", zh: "林没有抢话，只是笑了笑。" },
      { de: "Zum ersten Mal seit dem Einzug [[kam]] ihr der Job nicht mehr wie ein Unfall [[vor|vorkommen]].", zh: "自从入职以来，这份工作第一次在她看来不再像一场意外。" },
    ],
  },
  {
    id: "umzug",
    title: "Zwei Ämter und ein Vertrag",
    kicker: "Jonas",
    blurb: "搬家、登记、差点把钱交给一个假官员。",
    sentences: [
      { de: "Jonas [[zog]] an einem grauen Dienstag [[um|umziehen]] und [[stand]] um sieben vor dem Bürgeramt.", zh: "一个阴沉的周二，约纳斯搬家了，七点就站在市民局门口。" },
      { de: "Zuerst [[meldete]] er sich in der alten Stadt [[ab|abmelden]], dann hier [[an|anmelden]]; die Adresse musste er noch [[ummelden|anmelden / ummelden]].", zh: "他先在旧城注销，再在这里登记；住址还得办变更。" },
      { de: "In der Schlange [[meldete|sich melden]] er sich erst, als eine Nummer aufleuchtete.", zh: "排队时直到号码亮起他才举手应到。" },
      { de: "Am Schalter sollte er Daten [[angeben]], sie [[eingeben]] und eine Gebühr zahlen, die die Stadt gerade [[angehoben|anheben]] hatte.", zh: "窗口要他填写并输入资料，还要交一笔市政刚上调的费用。" },
      { de: "Bargeld [[hob]] er danach am Automaten [[ab|abheben]].", zh: "随后他在机器上取了现金。" },
      { de: "Vor dem Haus [[kam]] ein Mann auf ihn [[zu|zukommen]], [[gab]] sich als Beamter [[aus|ausgeben]] und wollte den Vertrag gleich mitnehmen.", zh: "房前有人向他走来，冒充官员，想把合同立刻拿走。" },
      { de: "Jonas [[verstand]] den Trick spät, aber noch rechtzeitig.", zh: "约纳斯识破得晚，但还算及时。" },
      { de: "Er [[gab]] dem Mann nichts [[über|übergeben]], [[hielt]] den Umschlag [[fest|festhalten]] und [[ging]] zurück ins Amt.", zh: "他什么也没交给那人，抓紧信封，走回局里。" },
      { de: "Die Sachbearbeiterin [[nahm]] ihm den Ausweis [[ab|abnehmen]], [[prüfte]] die Mappe und [[vermeldete]] nur trocken, solche Betrüger [[kämen]] in letzter Zeit öfter [[vor|vorkommen]].", zh: "办事员把他的证件接过去，检查文件夹，只干巴巴地说：这种骗子最近更常见了。" },
      { de: "Den Mietvertrag [[schloss]] Jonas am Nachmittag mit der Hausverwaltung [[ab|abschließen]].", zh: "下午他和物业签了租约。" },
      { de: "Die Nachbarin Frau Berger [[ließ]] ihn ins Haus [[ein|einlassen]], [[überließ]] ihm den Zweitschlüssel und [[hinterließ]] auf dem Küchentisch eine Nummer für den Notfall.", zh: "邻居贝格尔太太放他进门，把备用钥匙交给他，并在厨房桌上留下应急电话。" },
      { de: "Jonas [[nahm]] die Hilfe [[an|annehmen]].", zh: "约纳斯接受了帮助。" },
      { de: "Am Abend [[hob]] er den Vertrag vom Boden [[auf|aufheben]], [[legte]] ihn in die Schublade und [[schloss]] sie [[ab|abschließen]].", zh: "晚上他把合同从地上捡起，放进抽屉，锁上。" },
      { de: "Draußen [[ging]] die Sonne [[unter|untergehen]].", zh: "外面太阳落下。" },
      { de: "Zum ersten Mal seit Tagen [[ließ]] der Lärm im Kopf [[nach|nachlassen]].", zh: "几天来，脑子里的噪音第一次小了下去。" },
      { de: "Er [[nahm]] sich [[vor|vornehmen]], Frau Berger am Wochenende zum Kaffee [[einzuladen|einladen]] – nicht aus Pflicht, sondern weil er sich auf sie [[verlassen|verlassen]] hatte, als es darauf [[ankam|ankommen]].", zh: "他打算周末请贝格尔太太喝咖啡——不是出于义务，而是因为关键时刻他信赖过她。" },
    ],
  },
  {
    id: "bruecke",
    title: "Die Brücke",
    kicker: "Nora",
    blurb: "记者跟着一座桥的争论，从集会走到议会决议。",
    sentences: [
      { de: "Nora [[arbeitete]] seit drei Jahren für das Stadtblatt und [[sollte]] die Debatte um die neue Brücke [[begleiten|begleiten]].", zh: "诺拉为市报干了三年，这次要跟踪新桥争论。" },
      { de: "Viele [[gingen]] von der Idee [[aus|ausgehen]], die Brücke bringe nur Stau in die Altstadt.", zh: "许多人一上来就认定：这座桥只会把拥堵带进老城。" },
      { de: "Das Thema [[ging]] nicht nur Autofahrer [[an|angehen]]; es [[ging]] Ladenbesitzer, Schulen und die Buslinie [[an|angehen]].", zh: "这不只关系到开车的人，也关系到店主、学校和公交线。" },
      { de: "Nora [[ging]] die Akten [[durch|durchgehen]], [[fand]] drei widersprüchliche Gutachten [[heraus|herausfinden]] und [[legte]] die Zahlen in einem Artikel [[dar|darlegen]].", zh: "她把卷宗过了一遍，查出三份互相打架的鉴定，并在文章里把数字摊开。" },
      { de: "Am Samstag [[hielt]] ein Verein eine Versammlung [[ab|abhalten]].", zh: "周六一个协会举行集会。" },
      { de: "Manche wollten die Planung ganz [[umgehen]]; andere wollten mit der Stadt [[umgehen]], bevor etwas [[beschlossen|beschließen]] wurde.", zh: "有人想彻底绕开规划；另一些人想在决议之前先和市政打交道。" },
      { de: "Ein Redner [[ging]] die Gegenseite einfach [[über|übergehen]] und [[teilte]] nur Kritik [[aus|austeilen]].", zh: "一位发言人直接略过对方，只会大加批评。" },
      { de: "Nora [[hielt]] sich [[zurück|zurückhalten]], [[hielt]] aber jedes Argument [[fest|festhalten]].", zh: "诺拉没有插话，却把每条论据都记下。" },
      { de: "Abends [[verfasste|verfassen]] sie den Bericht, [[fasste]] ihn kurz [[zusammen|zusammenfassen]] und [[gab]] ihn an die Redaktion [[weiter|weitergeben]].", zh: "晚上她写好报道，短短概括，交给编辑部。" },
      { de: "Die Chefin [[strich]] zwei Sätze, weil eine Behauptung nicht [[belegt|belegen]] war, und [[legte]] Nora nahe, den Ton zu [[mildern|mildern]].", zh: "上司删了两句，因为有个说法没有证据，并暗示诺拉把语气放缓。" },
      { de: "Nora [[widerlegte]] eine Zahl aus dem Flugblatt, ohne den Autor vorzuführen.", zh: "她驳斥了传单上的一个数字，却没有当众羞辱作者。" },
      { de: "Am Dienstag [[beschloss]] der Rat den Kompromiss: die Brücke ja, aber schmaler, und ein Uferweg sollte mit [[erschlossen|erschließen]] werden.", zh: "周二议会通过折中案：桥要建，但更窄，并同时开发一条河岸路。" },
      { de: "Nora [[stand]] auf der Tribüne, als die Abstimmung [[stattfand|stattfinden]].", zh: "表决举行时，诺拉站在旁听席上。" },
      { de: "Eine Fraktion [[enthielt]] sich; der Rest [[nahm]] das Ergebnis [[hin|hinnehmen]].", zh: "一个党团弃权；其余人接受了结果。" },
      { de: "Draußen [[ging]] die Sonne [[auf|aufgehen]], und zum ersten Mal seit Wochen [[kam]] Nora der Streit nicht mehr endlos [[vor|vorkommen]].", zh: "外面太阳升起，几周来这争论第一次在她看来不再没完没了。" },
      { de: "Sie [[schloss]] das Notizbuch [[ab|abschließen]], [[ließ]] den Ärger [[los|loslassen]] und [[ging]] zu Fuß über die alte Brücke nach Hause – solange es sie noch gab.", zh: "她合上笔记本，把火气放开，步行走过旧桥回家——趁它还在。" },
    ],
  },
  {
    id: "verein",
    title: "Was der Verein noch zusammenhält",
    kicker: "Lea",
    blurb: "欠费、争吵、一次坦白，协会差点散掉。",
    sentences: [
      { de: "Lea [[unterhielt]] seit zwei Jahren die Website des Kulturvereins und [[hielt]] die Termine [[ein|einhalten]], die sonst niemand im Kopf [[behielt|behalten]].", zh: "两年来莉娅维护着文化协会的网站，别人记不住的期限都是她在遵守。" },
      { de: "Im März [[stand]] eine Rechnung [[aus|ausstehen]], und niemand wollte dafür [[aufkommen]].", zh: "三月有一笔账还挂着，谁也不愿承担。" },
      { de: "Ein Mitglied, das Lea kaum [[ausstehen]] konnte, [[hielt]] ihr vor, sie [[halte]] Informationen [[zurück|zurückhalten]].", zh: "一个她几乎受不了的会员指责她隐瞒信息。" },
      { de: "Die Stimmung [[wäre]] fast [[gekippt|kippen]].", zh: "气氛差一点点就要翻。" },
      { de: "Lea [[setzte]] eine Versammlung [[an|ansetzen]] und [[legte]] die Kontoauszüge auf den Tisch.", zh: "莉娅定了一次集会，把对账单摊在桌上。" },
      { de: "Tom [[gestand]] endlich, dass er eine Überweisung [[unterlassen]] hatte, nicht aus Bosheit, sondern weil er den Termin [[verlegt|verlegen]] und dann [[vergessen|vergessen]] hatte.", zh: "汤姆终于承认：他漏转了一笔账，不是出于恶意，而是改过期后来忘了。" },
      { de: "Die anderen [[vergaben]] ihm die Panne, [[vergaben]] den Druckauftrag neu und [[beschlossen]], die Kasse künftig zu [[teilen|teilen]].", zh: "别人原谅了这次失误，把印刷单重新发包，并决定以后账目分开管。" },
      { de: "Lea [[nahm]] das Angebot [[an|annehmen]], die Kasse mit Tom gemeinsam zu [[führen|führen]].", zh: "莉娅接受了和汤姆共管出纳的提议。" },
      { de: "Sie [[verstand]] sich plötzlich besser mit ihm, als beide dieselben Zahlen [[vor sich hatten|haben]].", zh: "两人都对着同一批数字时，她突然跟他合得来了。" },
      { de: "Am Abend [[begingen]] sie trotzdem das kleine Sommerfest, das schon lange im Kalender [[stand|stehen]].", zh: "晚上他们还是举办了日历上早就写着的小型夏日节。" },
      { de: "Lea [[teilte]] Kuchen [[aus|austeilen]], [[teilte]] den Gästen die neue Regelung [[mit|mitteilen]] und [[hielt]] eine kurze Rede.", zh: "她分发蛋糕，把新规矩告知来宾，并作了简短发言。" },
      { de: "Als der Platz dunkel wurde, [[ließen]] sie die Musik [[nach|nachlassen]] und [[schlossen]] die Tür [[ab|abschließen]].", zh: "场地暗下来时，他们把音乐放小，锁上门。" },
      { de: "Lea [[blieb]] noch eine Viertelstunde, [[arbeitete]] die peinliche Woche in Gedanken [[auf|aufarbeiten]] und [[fand]] sich damit [[ab|abfinden]], dass Vereine aus solchen Abenden bestehen – nicht aus perfekten Protokollen.", zh: "莉娅又留了一刻钟，在脑子里把这尴尬的一周清理一遍，并接受了：协会靠的是这样的夜晚，不是完美的会议记录。" },
    ],
  },
  {
    id: "schluessel",
    title: "Der Schlüssel unter der Matte",
    kicker: "Alltag",
    blurb: "一把钥匙、一次感冒、邻居把人接回家。",
    sentences: [
      { de: "Am Donnerstag [[fand]] Mara den Wohnungsschlüssel nicht, den sie morgens noch [[vorgefunden|vorfinden]] hatte.", zh: "周四玛拉找不到那把早上还见过的钥匙。" },
      { de: "Sie [[hatte]] ihn offenbar [[verlegt|verlegen]].", zh: "显然是她放错地方了。" },
      { de: "Lin, die im selben Haus wohnte, [[kam]] ihr im Treppenhaus [[entgegen|entgegenkommen]] und [[nahm]] ihr die Einkaufstasche [[ab|abnehmen]].", zh: "同住一栋楼的林在楼梯间迎上来，接过她的购物袋。" },
      { de: "Mara [[hatte]] Fieber und wollte niemandem zur Last fallen, [[ließ]] sich dann aber doch [[ein|einlassen]] auf die Hilfe.", zh: "玛拉在发烧，本不想麻烦人，但还是让自己接受了帮助。" },
      { de: "Frau Berger [[schloss]] auf, [[ließ]] die beiden [[ein|einlassen]] und [[setzte]] Wasser [[auf|aufsetzen]].", zh: "贝格尔太太开门，放她们进来，烧上水。" },
      { de: "Der Schlüssel [[lag]] unter der Fußmatte; Jonas hatte ihn nach dem Sport [[hingelegt|legen]] und niemandem [[mitgeteilt|mitteilen]].", zh: "钥匙在门垫下；约纳斯运动后随手放下，谁也没告诉。" },
      { de: "Er [[gesteht]] das später, rot im Gesicht.", zh: "后来他红着脸承认了。" },
      { de: "Mara [[vergab]] es ihm sofort; sie [[konnte]] an diesem Tag sowieso kaum [[aufrecht stehen|stehen]].", zh: "玛拉马上原谅了他；那天她本来也快站不稳了。" },
      { de: "Lin [[setzte]] sie aufs Sofa, [[nahm]] eine Decke vom Stuhl [[herunter|herunternehmen]] und [[blieb]] sitzen, bis das Fieber ein wenig [[nachließ|nachlassen]].", zh: "林把她安到沙发上，从椅子上拿了毯子，一直坐到烧退了一点。" },
      { de: "Unten im Hof [[ging]] die Sonne [[unter|untergehen]].", zh: "院子里太阳落下。" },
      { de: "Oben in der Küche [[unterhielten]] sie sich leise, damit Mara schlafen [[konnte|können]].", zh: "厨房里他们小声聊天，好让玛拉能睡。" },
      { de: "Niemand [[hielt]] dem anderen etwas [[vor|vorhalten]].", zh: "谁也没有指责谁。" },
      { de: "Es [[kam]] nur darauf [[an|ankommen]], dass die Tür wieder aufging und niemand allein im Flur stehen blieb.", zh: "关键只是门重新能打开，走廊里没有人独自呆着。" },
      { de: "Als Mara später [[aufstand|aufstehen]], [[fand]] sie auf dem Tisch eine Notiz: Schlüssel im Fach, Suppe im Topf, einfach [[anrufen|anrufen]].", zh: "玛拉后来起身时，桌上有张条子：钥匙在格子里，汤在锅里，直接打电话。" },
      { de: "Sie [[fasste]] sich, lächelte und [[dachte]] zum ersten Mal seit der Prüfung nicht an Noten, sondern daran, dass dieses Haus nicht [[wegzudenken|wegdenken]] war.", zh: "她让自己定了定神，笑了：考试以来第一次，她想的不是分数，而是这栋房子已经不可或缺。" },
    ],
  },
];
